### ISSUE TITLE
Need a way to scroll through pages of choice buttons

### ISSUE THREAD

**Issue by Kittery** [FallowWing/Interphore#21]
- Choice buttons real estate is quite tight though
- Might wanna put small arrow buttons above the choices, on either side of the screen
- Just use rects and I'll make assets later, if you decide to go with that
- Alternatively, we could drop the number of choices down to 3, and split the last slot in half for the arrows, like this: https://i.imgur.com/ZNKzhxv.png

**Comment by FallowWing** [comment]
This was added in the new engine. https://github.com/FallowWing/Interphore/commit/72e1b74126f52181ae1b72fc3b786ee8de667353
