### ISSUE TITLE
spr.alpha changes sometimes don't take effect when combined with tint

### ISSUE THREAD

**Issue by Kittery** [FallowWing/Interphore#22]
spr.alpha = 0.5 or spr.alpha = 0 do not appear to change visibility when also tinting a sprite

Internal -> Scratch -> Titlescreen Test (look at the duplicate of the character art, cartBG)

scratch.phore ln #93

**Comment by FallowWing** [comment]
Fixed tint in core engine, test is missing to confirm alpha. Assuming it was never an issue.
