### ISSUE TITLE
New Next and Back buttons on either side of the choice buttons have no graphic

### ISSUE THREAD

**Issue by Kittery** [FallowWing/Interphore#37]
Should be the standard choice button 9slice and then an arrow graphic which I made, filepath

sourceAssets/img/writer/choiceArrow

flipped one way for Next and the other way for Back obvs

**Comment by FallowWing** [comment]
Added here. https://github.com/FallowWing/Interphore/commit/d06e9a014eba86028fb1f692390ca15ca0b61c97
