### ISSUE TITLE
Text is hard to read on Android

### ISSUE THREAD

**Issue by Kittery** [FallowWing/Interphore#5]
May be due to locked portrait mode!

If not, we could add a x2 text size mode for mobile?
We have enough empty space in the buttons to support it I think
Needs thought/discussion

**Comment by Ryonez** [comment]
Will confirm. The text is small enough to make it completely uncomfortable to play.

Using a Galaxy S7e with WQHD mode on (2560*1440).

**Comment by FallowWing** [comment]
Default text was resized. https://github.com/FallowWing/Interphore/commit/aaa3ccc424629f6746fc3cc951a265499d064030
And some specific elements. https://github.com/FallowWing/Interphore/commit/e5805ff2bc11dfacc1f44af3d0999114ecda97aa

Closing for now, although there's should probably be a new issue citing the newly created layout issues in some parts of the ui.
