### ISSUE TITLE
Prettier text input fields

### ISSUE THREAD

**Issue by Kittery** [FallowWing/Interphore#6]
They can still float above the buttons as they are now, just need more indication that you can type in them, which might entail:
- Hover effect/noise
- Click effect/noise + flashing cursor
- Support for a title above them, which might say TYPE HERE: or ENTER NAME: or whatever

**Comment by FallowWing** [comment]
Added cursor here. https://github.com/FallowWing/Interphore/commit/08c94f6ca192e09341cbc275ea12949097e596ca

And title here. https://github.com/FallowWing/Interphore/commit/d7c4306f5dcd4ecb586a5abadfa0fde4266ba9b8
